-- MySQL Script generated by MySQL Workbench
-- czw, 29 mar 2018, 18:29:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meetpin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meetpin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meetpin` DEFAULT CHARACTER SET utf8 ;
USE `meetpin` ;

-- -----------------------------------------------------
-- Table `meetpin`.`userId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meetpin`.`userId` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetpin`.`relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meetpin`.`relationship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_one_id` INT NOT NULL,
  `user_two_id` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `action_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_one_id`, `user_two_id`, `action_user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_idx` (`user_one_id` ASC),
  INDEX `fk_relationship_1_idx` (`user_two_id` ASC),
  INDEX `fk_rel_idx` (`action_user_id` ASC),
  CONSTRAINT `fk_rel_user_one`
    FOREIGN KEY (`user_one_id`)
    REFERENCES `meetpin`.`userId` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_user_two`
    FOREIGN KEY (`user_two_id`)
    REFERENCES `meetpin`.`userId` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_user_action`
    FOREIGN KEY (`action_user_id`)
    REFERENCES `meetpin`.`userId` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetpin`.`pin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meetpin`.`pin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `message` VARCHAR(200) NULL,
  `map_latitude` DECIMAL(10,8) NOT NULL,
  `map_longitude` DECIMAL(11,8) NOT NULL,
  `meeting_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expire` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_pin_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `meetpin`.`userId` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetpin`.`pin_to_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meetpin`.`pin_to_friend` (
  `pin_id` INT NOT NULL,
  `to_user_id` INT NOT NULL,
  PRIMARY KEY (`pin_id`, `to_user_id`),
  UNIQUE INDEX `pin_id_UNIQUE` (`pin_id` ASC),
  INDEX `fk_friend_idx` (`to_user_id` ASC),
  CONSTRAINT `fk_pin`
    FOREIGN KEY (`pin_id`)
    REFERENCES `meetpin`.`pin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `meetpin`.`userId` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetpin`.`pin_to_global`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meetpin`.`pin_to_global` (
  `pin_id` INT NOT NULL,
  PRIMARY KEY (`pin_id`),
  CONSTRAINT `fk_pin_to_global_pin1`
    FOREIGN KEY (`pin_id`)
    REFERENCES `meetpin`.`pin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetpin`.`pin_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meetpin`.`pin_answer` (
  `pin_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `answer` TINYINT NOT NULL,
  PRIMARY KEY (`pin_id`, `user_id`),
  INDEX `fk_user_answer_idx` (`user_id` ASC),
  CONSTRAINT `fk_pin_answer`
    FOREIGN KEY (`pin_id`)
    REFERENCES `meetpin`.`pin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_answer`
    FOREIGN KEY (`user_id`)
    REFERENCES `meetpin`.`userId` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'client' IDENTIFIED BY 'client123';

GRANT SELECT ON TABLE `meetpin`.* TO 'client';
CREATE USER 'server' IDENTIFIED BY 'server123';

GRANT ALL ON `meetpin`.* TO 'server';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
